#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

helper="$repo_root/skills/implementaudit/scripts/summarize-repo.sh"

# 1. In a minimal repo with no checkers, candidate discovery offers only the
#    universal baseline command — no hardcoded IMPLEMENTAUDIT paths.
mkdir -p "$tmp/bare"
(
  cd "$tmp/bare"
  git init -q
  printf '# bare\n' > README.md
  git add README.md
  git -c user.email=test@example.invalid -c user.name=test commit -qm init
  bash "$helper" > out.log 2>&1
)
grep -q "git diff --check" "$tmp/bare/out.log" || {
  printf 'summarize-repo.test: baseline candidate missing in bare repo\n' >&2
  exit 1
}
if grep -q "bash scripts/check-" "$tmp/bare/out.log"; then
  printf 'summarize-repo.test: hardcoded checker candidates leaked into bare repo\n' >&2
  exit 1
fi

# 2. In a repo that has checkers and focused tests, discovery offers them.
mkdir -p "$tmp/rich/scripts" "$tmp/rich/tests"
(
  cd "$tmp/rich"
  git init -q
  printf '#!/usr/bin/env bash\ntrue\n' > scripts/check-example.sh
  printf '#!/usr/bin/env bash\ntrue\n' > scripts/verify-package.sh
  printf '#!/usr/bin/env bash\ntrue\n' > tests/example.test.sh
  git add -A
  git -c user.email=test@example.invalid -c user.name=test commit -qm init
  bash "$helper" > out.log 2>&1
)
grep -q "bash scripts/check-example.sh" "$tmp/rich/out.log" || {
  printf 'summarize-repo.test: discovered checker candidate missing\n' >&2
  exit 1
}
grep -q "bash scripts/verify-package.sh" "$tmp/rich/out.log" || {
  printf 'summarize-repo.test: verify-package candidate missing\n' >&2
  exit 1
}
grep -q "bash tests/example.test.sh" "$tmp/rich/out.log" || {
  printf 'summarize-repo.test: discovered test candidate missing\n' >&2
  exit 1
}

# #76 R3-F3/F4/F5: generated-owner detection blocks direct output edits,
# permits the generator, and preserves an explicit hand-authored control.
mkdir -p "$tmp/generated/tools"
printf '<!-- DO NOT EDIT: generated by tools/build_report.py -->\nreport\n' \
  > "$tmp/generated/report.md"
printf 'print("build")\n' > "$tmp/generated/tools/build_report.py"
printf 'bash tools/build_report.py --check report.md\n' > "$tmp/generated/check.sh"
if (cd "$tmp/generated" && bash "$helper" --generated-owner report.md >/dev/null 2>&1); then
  printf 'summarize-repo.test: generated output classified as directly editable\n' >&2
  exit 1
fi
(cd "$tmp/generated" && bash "$helper" --generated-owner tools/build_report.py >/dev/null) || {
  printf 'summarize-repo.test: generator source was blocked\n' >&2
  exit 1
}
printf '{"generator": "hand-authored"}\n' > "$tmp/generated/data.json"
(cd "$tmp" && bash "$helper" --generated-owner generated/data.json >/dev/null) || {
  printf 'summarize-repo.test: declared hand-authored control was blocked\n' >&2
  exit 1
}
printf 'root-report.md --check byte-identical\n' > "$tmp/generated/Makefile"
printf 'report\n' > "$tmp/generated/root-report.md"
if (cd "$tmp/generated" && bash "$helper" --generated-owner root-report.md >/dev/null 2>&1); then
  printf 'summarize-repo.test: root Makefile generation gate was missed\n' >&2
  exit 1
fi
printf '<!-- DO NOT EDIT -->\n{"generator": "hand-authored"}\n' \
  > "$tmp/generated/contradictory.json"
if (cd "$tmp/generated" && bash "$helper" --generated-owner contradictory.json >/dev/null 2>&1); then
  printf 'summarize-repo.test: contradictory generator authority was accepted\n' >&2
  exit 1
fi

printf 'summarize-repo.test: ok\n'
