#!/usr/bin/env bash
set -euo pipefail

printf 'implementaudit.summarize-repo\n'
printf 'side_effects=none\n'

if git rev-parse --show-toplevel >/dev/null 2>&1; then
  git status --short --branch
  printf '\nrecent-churn:\n'
  git log --oneline -n 8 2>/dev/null || printf 'no-commits-yet\n'
  printf '\ntracked-files:\n'
  git ls-files | sed -n '1,120p'
else
  printf 'not a git repo\n'
  find . -maxdepth 3 -type f | sort | sed -n '1,120p'
fi

printf '\nrepo-instructions:\n'
find . -maxdepth 3 \( -name AGENTS.md -o -name CONTRIBUTING.md -o -name README.md \) -print | sort

printf '\ncanonical-owners:\n'
for path in SKILL.md AGENTS.md README.md CHANGELOG.md scripts/verify-package.sh .github/workflows/validate.yml; do
  if [ -e "$path" ]; then printf '%s\n' "$path"; fi
done

printf '\nchecks-and-smokes:\n'
find scripts skills/scripts tests -maxdepth 2 -type f 2>/dev/null | sort | sed -n '1,120p' || true

printf '\nmandatory-command-candidates:\n'
printf '%s\n' "git diff --check"
# Candidates are discovered from the target repo, not hardcoded: only scripts
# and focused tests that actually exist are offered.
if [ -e scripts/verify-package.sh ]; then
  printf 'bash %s\n' "scripts/verify-package.sh"
fi
for script in scripts/check-*.sh tests/*.test.sh; do
  if [ -e "$script" ]; then
    printf 'bash %s\n' "$script"
  fi
done

printf '\ntest-surface-summary:\n'
for dir in tests test spec __tests__; do
  if [ -d "$dir" ]; then
    printf '%s: %d test files\n' "$dir" "$(find "$dir" -type f -name '*.test.*' -o -name '*.spec.*' 2>/dev/null | wc -l)"
  fi
done
# Count test files in src/ subdirs too
stcount=$(git ls-files 2>/dev/null | grep -cE '\.(test|spec)\.[a-z]+$' || true)
printf 'tracked-test-files: %d\n' "$stcount"

printf '\nfile-extension-counts:\n'
git ls-files 2>/dev/null | grep -oE '\.[^./]+$' | sort | uniq -c | sort -rn | head -20 || true

printf '\nrecently-churned-files:\n'
git log --oneline --diff-filter=M --name-only -n 10 2>/dev/null | grep -v '^[a-f0-9]' | sort | uniq -c | sort -rn | head -15 || true

printf '\nlargest-tracked-files:\n'
git ls-files 2>/dev/null | xargs -d '\n' du -k 2>/dev/null | sort -rn | head -15 || true

printf '\nlikely-generated-outputs:\n'
git ls-files 2>/dev/null | grep -E '(dist/|build/|out/|\.min\.(js|css)|\.d\.ts$|generated|\.lock$)' | head -20 || true
grep -R -l -I 'DO NOT EDIT\|auto-generated\|generated by' . --exclude-dir=.git 2>/dev/null | head -10 || true

printf '\nmandatory-command-candidates-from-scripts:\n'
if [ -f package.json ]; then
  node -pe "
    var s=require('./package.json').scripts||{};
    ['build','test','lint','typecheck','check','validate','ci']
      .filter(k=>s[k]).map(k=>'npm run '+k).join('\n')
  " 2>/dev/null || true
fi
for f in scripts/verify-package.sh scripts/build-release-asset.sh Makefile justfile; do
  if [ -f "$f" ]; then printf 'candidate: bash %s\n' "$f"; fi
done
if [ -f Makefile ]; then
  grep -E '^[a-zA-Z][a-zA-Z0-9_-]+:' Makefile 2>/dev/null | head -10 | sed 's/:.*//' | awk '{printf "make %s\n", $0}' || true
fi

printf '\nfixtures-and-examples:\n'
find fixtures -maxdepth 3 -type f 2>/dev/null | sort | sed -n '1,120p' || true

printf '\nrelease-boundaries:\n'
for path in scripts/build-release-asset.sh scripts/write-release-checksums.sh dist .claude-plugin/plugin.json .claude-plugin/marketplace.json; do
  if [ -e "$path" ]; then printf '%s\n' "$path"; fi
done

printf '\nrun-root-boundaries:\n'
printf 'preferred_base=.IMPLEMENTAUDIT/runs\n'
printf 'claim_helper=%s/scripts/claim-run.sh\n' "${IMPLEMENTAUDIT_SKILL_DIR:-skills/implementaudit}"
printf 'legacy_flat=.IMPLEMENTAUDIT/ROADMAP.md .IMPLEMENTAUDIT/STATE.md .IMPLEMENTAUDIT/THINKING.md .IMPLEMENTAUDIT/PROTOCOL.md\n'
printf 'parallel_source_editing=requires_separate_git_worktrees\n'

printf '\nsidecar-boundaries:\n'
printf 'graphify=optional_orientation_not_proof\n'
printf 'activegraph=optional_custody_not_correctness_proof\n'
printf 'markdown_fallback=first_class\n'

printf '\npossible-generated-artifacts:\n'
grep -R -n -I \
  -e 'DO NOT EDIT' \
  -e 'generated by' \
  -e 'auto-generated' \
  -e 'this file is generated' \
  . --exclude-dir=.git 2>/dev/null | sed -n '1,40p' || true

printf '\nlikely-regression-surfaces:\n'
for path in skills scripts tests fixtures README.md CHANGELOG.md AGENTS.md docs/diagrams docs/audits .github/workflows; do
  if [ -e "$path" ]; then printf '%s\n' "$path"; fi
done
