#!/usr/bin/env bash
set -euo pipefail

if [ "${1:-}" = "--generated-owner" ]; then
  target="${2:-}"
  [ "$#" -eq 2 ] && [ -f "$target" ] && [ ! -L "$target" ] || {
    printf 'summarize-repo: --generated-owner requires a regular non-symlink file\n' >&2
    exit 2
  }
  if command -v python >/dev/null 2>&1; then py_cmd=(python)
  elif command -v python3 >/dev/null 2>&1; then py_cmd=(python3)
  elif command -v py >/dev/null 2>&1; then py_cmd=(py -3)
  else printf 'summarize-repo: python is required\n' >&2; exit 2
  fi
  "${py_cmd[@]}" - "$target" <<'PY'
import os
import pathlib
import re
import sys

target = pathlib.Path(sys.argv[1])
text = target.read_text(encoding="utf-8")
hand_authored = re.search(
    r"(?<![\w-])[\"']?generator[\"']?\s*:\s*[\"']?hand-authored[\"']?(?![\w-])",
    text,
    re.I,
)
marker = re.search(r"(?:DO NOT EDIT|auto-generated|generated by|this file is generated)", text, re.I)
path_signal = any(part.casefold() in {"dist", "build", "out", "generated"}
                  for part in target.parts)
owner_match = re.search(r"generated by\s+([^\s<>]+)", text, re.I)
owner = owner_match.group(1).rstrip("-:;,.") if owner_match else "unknown"
gates = []
needle = target.as_posix()
search_bases = (
    pathlib.Path("scripts"),
    pathlib.Path("tools"),
    pathlib.Path("tests"),
    pathlib.Path(".github/workflows"),
)
candidate_paths = []
for base in search_bases:
    if not base.is_dir():
        continue
    for path in sorted(base.rglob("*")):
        if path.is_symlink() or not path.is_file():
            continue
        candidate_paths.append(path)
for name in (
    "Makefile", "makefile", "GNUmakefile", "justfile", "Justfile",
    "package.json", "pyproject.toml", "tox.ini", "noxfile.py",
):
    path = pathlib.Path(name)
    if path.is_file() and not path.is_symlink():
        candidate_paths.append(path)
for path in sorted(set(candidate_paths)):
    try:
        candidate = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        continue
    if needle in candidate and re.search(r"--check|regenerat|byte-identical", candidate, re.I):
        gates.append(path.as_posix())
generated_signals = bool(marker or path_signal or gates)
if hand_authored and (marker or gates):
    print(
        f"summarize-repo: contradictory generator authority for {target.as_posix()}: "
        f"hand-authored declaration plus generated signals",
        file=sys.stderr,
    )
    raise SystemExit(1)
if hand_authored:
    print(f"hand-authored: {target.as_posix()} | declaration: generator: hand-authored")
    raise SystemExit(0)
if generated_signals:
    print(f"generated: {target.as_posix()} | generator: {owner} | gates: {','.join(gates) or 'none'}")
    raise SystemExit(1)
print(f"hand-authored: {target.as_posix()} | generated-signals: none")
PY
  exit $?
fi

printf 'implementaudit.summarize-repo\n'
printf 'side_effects=none\n'

if git rev-parse --show-toplevel >/dev/null 2>&1; then
  git status --short --branch
  printf '\nrecent-churn:\n'
  git log --oneline -n 8 2>/dev/null || printf 'no-commits-yet\n'
  printf '\ntracked-files:\n'
  git ls-files | sed -n '1,120p'
else
  printf 'not a git repo\n'
  find . -maxdepth 3 -type f | sort | sed -n '1,120p'
fi

printf '\nrepo-instructions:\n'
find . -maxdepth 3 \( -name AGENTS.md -o -name CONTRIBUTING.md -o -name README.md \) -print | sort

printf '\ncanonical-owners:\n'
for path in SKILL.md AGENTS.md README.md CHANGELOG.md scripts/verify-package.sh .github/workflows/validate.yml; do
  if [ -e "$path" ]; then printf '%s\n' "$path"; fi
done

printf '\nchecks-and-smokes:\n'
find scripts skills/scripts tests -maxdepth 2 -type f 2>/dev/null | sort | sed -n '1,120p' || true

printf '\nmandatory-command-candidates:\n'
printf '%s\n' "git diff --check"
# Candidates are discovered from the target repo, not hardcoded: only scripts
# and focused tests that actually exist are offered.
if [ -e scripts/verify-package.sh ]; then
  printf 'bash %s\n' "scripts/verify-package.sh"
fi
for script in scripts/check-*.sh tests/*.test.sh; do
  if [ -e "$script" ]; then
    printf 'bash %s\n' "$script"
  fi
done

printf '\ntest-surface-summary:\n'
for dir in tests test spec __tests__; do
  if [ -d "$dir" ]; then
    printf '%s: %d test files\n' "$dir" "$(find "$dir" -type f -name '*.test.*' -o -name '*.spec.*' 2>/dev/null | wc -l)"
  fi
done
# Count test files in src/ subdirs too
stcount=$(git ls-files 2>/dev/null | grep -cE '\.(test|spec)\.[a-z]+$' || true)
printf 'tracked-test-files: %d\n' "$stcount"

printf '\nfile-extension-counts:\n'
git ls-files 2>/dev/null | grep -oE '\.[^./]+$' | sort | uniq -c | sort -rn | head -20 || true

printf '\nrecently-churned-files:\n'
git log --oneline --diff-filter=M --name-only -n 10 2>/dev/null | grep -v '^[a-f0-9]' | sort | uniq -c | sort -rn | head -15 || true

printf '\nlargest-tracked-files:\n'
git ls-files 2>/dev/null | xargs -d '\n' du -k 2>/dev/null | sort -rn | head -15 || true

printf '\nlikely-generated-outputs:\n'
git ls-files 2>/dev/null | grep -E '(dist/|build/|out/|\.min\.(js|css)|\.d\.ts$|generated|\.lock$)' | head -20 || true
grep -R -l -I 'DO NOT EDIT\|auto-generated\|generated by' . --exclude-dir=.git 2>/dev/null | head -10 || true

printf '\nmandatory-command-candidates-from-scripts:\n'
if [ -f package.json ]; then
  node -pe "
    var s=require('./package.json').scripts||{};
    ['build','test','lint','typecheck','check','validate','ci']
      .filter(k=>s[k]).map(k=>'npm run '+k).join('\n')
  " 2>/dev/null || true
fi
for f in scripts/verify-package.sh scripts/build-release-asset.sh Makefile justfile; do
  if [ -f "$f" ]; then printf 'candidate: bash %s\n' "$f"; fi
done
if [ -f Makefile ]; then
  grep -E '^[a-zA-Z][a-zA-Z0-9_-]+:' Makefile 2>/dev/null | head -10 | sed 's/:.*//' | awk '{printf "make %s\n", $0}' || true
fi

printf '\nfixtures-and-examples:\n'
find fixtures -maxdepth 3 -type f 2>/dev/null | sort | sed -n '1,120p' || true

printf '\nrelease-boundaries:\n'
for path in scripts/build-release-asset.sh scripts/write-release-checksums.sh dist .claude-plugin/plugin.json .claude-plugin/marketplace.json; do
  if [ -e "$path" ]; then printf '%s\n' "$path"; fi
done

printf '\nrun-root-boundaries:\n'
printf 'preferred_base=.IMPLEMENTAUDIT/runs\n'
printf 'claim_helper=%s/scripts/claim-run.sh\n' "${IMPLEMENTAUDIT_SKILL_DIR:-skills/implementaudit}"
printf 'legacy_flat=.IMPLEMENTAUDIT/ROADMAP.md .IMPLEMENTAUDIT/STATE.md .IMPLEMENTAUDIT/THINKING.md .IMPLEMENTAUDIT/PROTOCOL.md\n'
printf 'parallel_source_editing=requires_separate_git_worktrees\n'

printf '\nsidecar-boundaries:\n'
printf 'graphify=optional_orientation_not_proof\n'
printf 'activegraph=optional_checkpoint_or_non_authoritative_mirror_not_correctness_proof\n'
printf 'markdown_fallback=first_class\n'

printf '\npossible-generated-artifacts:\n'
grep -R -n -I \
  -e 'DO NOT EDIT' \
  -e 'generated by' \
  -e 'auto-generated' \
  -e 'this file is generated' \
  . --exclude-dir=.git 2>/dev/null | sed -n '1,40p' || true

printf '\nlikely-regression-surfaces:\n'
for path in skills scripts tests fixtures README.md CHANGELOG.md AGENTS.md docs/diagrams docs/audits .github/workflows; do
  if [ -e "$path" ]; then printf '%s\n' "$path"; fi
done
